# Application bindings
bindd = SUPER, RETURN, Terminal, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, F, File manager, exec, uwsm-app -- nautilus --new-window
bindd = SUPER SHIFT, B, Browser, exec, omarchy-launch-browser
bindd = SUPER SHIFT ALT, B, Browser (private), exec, omarchy-launch-browser --private
bindd = SUPER SHIFT, N, Editor, exec, omarchy-launch-editor

# Display/Monitor switching binds
unbind = SUPER, P
bindd = SUPER, P, Select monitor mode, exec, ~/.config/hypr/scripts/monitor-switch.sh

# Lid switch auto display handling
bindl = , switch:off:Lid Switch, exec, ~/.config/hypr/scripts/monitor-switch.sh laptop
bindl = , switch:on:Lid Switch, exec, ~/.config/hypr/scripts/monitor-switch.sh lid_close


# Language switching bindings
bindd = SUPER ALT, 1, Language: English, exec, hyprctl switchxkblayout all 0
bindd = SUPER ALT, 2, Language: Ukrainian, exec, hyprctl switchxkblayout all 1
bindd = SUPER ALT, 3, Language: Russian, exec, hyprctl switchxkblayout all 2

# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# unbind = SUPER, SPACE
# bindd = SUPER, SPACE, Omarchy menu, exec, omarchy-menu

# Unbind SUPER + M if present
unbind = SUPER, M

# Unbind default PRINT keybinding and rebind to SUPER + \
unbind = , code:107
bindd = SUPER, backslash, Screenshot, exec, uwsm-app -- flameshot gui
